### ISSUE TITLE
Instructor Feedback - Week 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [supersonic405/LearningManagementSystem#1]
You have a good start here @supersonic405 and a solid project idea!

- [ ] From Week 2 Act 4: "Add a timeLog.md and then enter your time log entries from Week 1 and 2. If you prefer, you may choose to write journal entries to document your progress, problems solved, key learning points, and anything else you find useful to track. You should track all time spent on Ent Java work outside of class, not just indie project work."

**Comment by supersonic405** [comment]
Will do.
