### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by tjdombrowski** [supersonic405/LearningManagementSystem#2]
# Design/Code Review 1

### Reviewer: Tiresa Dombrowski

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| I found a few typos in your problem statement. In the first sentence, I think it should be students, not student. You also type "classed" instead of "classes" and "databae" instead of "database". Other than that, I think you summarize the issue and what you plan to do fairly well. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |  The flow makes sense, and I think you've got everything you need for the database represented. I think you just need to get some pictures of the screens up. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| The database seems simple and makes sense. I think the only thing you'll need to do is implement the many to many relationship xref table we talked about. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | No code yet to look at. |

**Comment by supersonic405** [comment]
Thank you for your feedback Tiresa. I have completed all the changes you suggested. Corrected typos, added code to .jsp files to represent what will be in each page and added code database to represent the many to many relationships.
