### ISSUE TITLE
Peer review feedback - Paul Norby

### ISSUE THREAD

**Issue by pnorby** [supersonic405/LearningManagementSystem#3]
# Design/Code Review 1

### Reviewer: Paul Norby

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Nice problem statement.  It looks like your application could really be used in your day to day at AmFam.  I would suggest cleaning up the readme and removing boiler plate code that doesn't apply to your project. You could also give a statement on what types of classes this application refers to.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | The application flow was nice and described the user experience well.  I could not access the screen designs however I could only view raw code.  You may want to use PNGs. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Good job keeping it simple.  I think that will help you to deliver a functioning application.  As we discussed, use a cross reference table to break up your many to many relationship with users and courses.  You may want to consider adding more fields so that users can get more information about a course.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.| Not much code yet I believe but I like how you are getting your back-end established first with your sql.  I would recommend visiting bootstrap's website asap as that will definitely help you with the responsiveness and look of your applications front-end.

**Comment by supersonic405** [comment]
Thank you for your feedback Paul. I have implemented your suggestions by; updating the readme file, moved the .jsp files with the initial content to the webapp folder,  add screenshots of screen design to the screens.md folder, and plan to add bootstrap formatting and validation as soon as I am able.
