### ISSUE TITLE
Instructor Feedback - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [supersonic405/LearningManagementSystem#4]
Looks like you have a good start flushing out what your application will do. I think the flow that you've created will be very useful in deciding what classes you need to build.  

- [x] ERD? Generating the diagram right in IntelliJ and putting the image here works, no need for anything special beyond that.
- [x] Some image links appear to be broken/missing in the screen design (Screens.md). 
- [x] JSPs - remember to use templating (includes or imports) to provide consistent sections of the jsps, such as headers, footers, nav bars, etc.
- [x] Looks like many of the Checkpoint 2 tasks are in progress.  Log4j, hibernate dao,and associated unit test/s.
- [x] Remember to check off completed issue items using - [x], and then close the issue when all tasks are complete. This applies to peer reviews too!

**Comment by supersonic405** [comment]
1. I have added ERDs to the DesignDocuments.
2. I'm working on the images links in Screens.md.
3. I have added headers to the .jsp files. Will add imports such as footers and nav bars, etc. as I learn more about them and discover samples.
4. Working on the class activities everyday after work and all day on weekends, I have not had time to add the Log4j, hibernate doa and associated test/s to my indie project. I have had my plate 100% full doing the weekly projects. 
5. Thanks for the reminder, I have and will continue to checked off completed issue items and also with peer reviews too.

**Comment by pawaitemadisoncollege** [comment]
Something very strange is going on when I attempt to add a new issue here. I've added three issues this evening and none seem to be showing up.  Not sure why... So I'm going to try appending it here:

Nice job getting your ERD up on GitHub!

- [ ] Log4J, Hibernate Dao, units tests and demonstration (screenshot ok) of code coverage is part of the checkpoint. Those who completed some weekly exercise tasks in their project already had some of that done; for those who did the scripted exercises, then those technologies/techniques needed to be completed within the indie project for the checkpoint.  You can always verify what needs to be completed in the indie project for a given checkpoint, or at the end of the semester, here: https://github.com/MadJavaEntFall2018/home/blob/master/IndividualProject.md.
- [ ] There's a broken link for Database Design at the bottom of readme.md
- [ ] Good work with the dev journal. Having that can be invaluable, especially when documenting problems and solutions. Be sure to remove some of the old info there (some 2016 stuff that looks familiar ;))
- [ ] Time log - it would be really helpful to see a breakdown of what tasks are taking a long time and what's going rather quickly. I may be able to point you to some other resources if there are particular areas that need more support.  This information would also be particularly helpful in evaluating workload for future students who may not have had Java or Adv Java at Madison College.
- [ ] jsp headers/footers/etc. - There's an example of how to include a jsp in another jsp in the Week1UserDisplayExercise here: https://github.com/MadJavaEntFall2018/week1-user-display-exercise-pawaitemadisoncollege/blob/e413811beb3de7e4d2c8b9c0d0804f760d9ccf89/src/main/webapp/index.jsp#L1. Essentially any duplicate lines of "code" in a jsp should moved into a separate jsp for inclusion. 
- [ ] ERD - is user needed the CourseCompletion table?  CourseCompletionStatus - is that user specific? What does login id represent on the course completion table?
- [ ] Screens - did I overlook screens to create, update, and delete courses, and the users taking those courses?
